### ISSUE TITLE
npm it?

### ISSUE THREAD

**Issue by FerchoCarcho** [tgdev/animate-sass#29]
Hello @tgdev 
Please, can you take it to npm? I would like to use it with node_modules

**Comment by hilja** [comment]
meanwhile `npm install --save-dev git+git@github.com:tgdev/animate-sass.git`

**Comment by blackfyre** [comment]
Or `yarn add https://github.com/tgdev/animate-sass.git`

**Comment by tgdev** [comment]
Hey @FerchoCarcho ,

Sorry for the delay. I'd be more than happy to add it to npm/yarn :-)

Will let you know when it's done!

**Comment by tgdev** [comment]
Please note someone else has forked this repo in order to publish it to NPM. Therefore you should be able to run

```bash
$ npm install animate-sass
```
I'm currently trying to contact the owner of the npm module to become a collaborator allowing me to update it when updates are made on this repo.

Finally, the readme of this repo has been updated to include installation instructions for npm and yarn
